AWSTemplateFormatVersion: 2010-09-09
Description: >-
  muz-aws-manager
Transform:
- AWS::Serverless-2016-10-31

Resources:
  # Lambda function
  stopAllInstancesHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/stop-all-instances/
      Handler: stop-all-instances.stopAllInstancesHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that stops all EC2 instances.
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:StopInstances
              Resource: "*"
      Events:
        ApiGatewayEndpoint: # Link to API Gateway
          Type: Api
          Properties:
            Path: /stop-all-instances
            Method: GET
      Metadata:
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: node22
          Sourcemap: false
          External:
            - aws-sdk

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
